# server.py
# Receives dashboard clicks, triggers agents, serves output files

from flask import Flask, request, jsonify, send_from_directory
import subprocess
import json
import os

app = Flask(__name__, static_folder='dashboard')

# ─── Serve Dashboard ──────────────────────────────────────────
@app.route('/')
def index():
    return send_from_directory('dashboard', 'index.html')

# ─── Save Settings ────────────────────────────────────────────
@app.route('/api/settings', methods=['POST'])
def save_settings():
    data = request.json
    niche         = data.get('niche', 'tech')
    platform      = data.get('platform', 'youtube')
    channel_style = data.get('channel_style', 'educational')

    config_content = f'''# config.py — auto-generated by dashboard
NICHE         = "{niche}"
PLATFORM      = "{platform}"
CHANNEL_STYLE = "{channel_style}"
'''
    with open('config.py', 'w') as f:
        f.write(config_content)

    return jsonify({"status": "ok", "message": "Settings saved"})


@app.route('/api/settings', methods=['GET'])
def get_settings():
    try:
        import importlib.util
        spec = importlib.util.spec_from_file_location("config", "config.py")
        config = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(config)
        return jsonify({
            "status": "ok",
            "niche": config.NICHE,
            "platform": config.PLATFORM,
            "channel_style": config.CHANNEL_STYLE
        })
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500



        
# ─── Run Agent ────────────────────────────────────────────────
@app.route('/api/run/<agent_name>', methods=['POST'])
def run_agent(agent_name):
    data            = request.json or {}
    selected_topic  = data.get('selected_topic', '')
    selected_hook   = data.get('selected_hook', '')

    # Build the prompt for Claude Code based on which agent to run
    prompts = {
        'research': (
            "Read AGENTS.md and follow the instructions under "
            "AGENT 1: Research Agent exactly. "
            "Read config.py for settings. "
            "Write output to outputs/topics.md"
        ),
        'hooks': (
            f"Read AGENTS.md and follow the instructions under "
            f"AGENT 2: Hook Factory exactly. "
            f"The user selected topic number {selected_topic}. "
            f"Read outputs/topics.md for the topics. "
            f"Write output to outputs/hooks.md"
        ),
        'script': (
            f"Read AGENTS.md and follow the instructions under "
            f"AGENT 3: Script Engine exactly. "
            f"The user selected hook number {selected_hook}. "
            f"Read outputs/hooks.md for the hooks. "
            f"Write output to outputs/script.md"
        ),
        'score': (
            "Read AGENTS.md and follow the instructions under "
            "AGENT 4: TRIBE v2 Script Scorer exactly. "
            "Read outputs/script.md. "
            "Write output to outputs/scores.json"
        ),
        'metadata': (
            "Read AGENTS.md and follow the instructions under "
            "AGENT 5: Metadata Agent exactly. "
            "Read outputs/script.md and outputs/scores.json. "
            "Write output to outputs/metadata.md"
        ),
        'repurpose': (
            "Read AGENTS.md and follow the instructions under "
            "AGENT 6: Repurpose Agent exactly. "
            "Read outputs/script.md. "
            "Write output to outputs/repurpose.md"
        ),
    }

    if agent_name not in prompts:
        return jsonify({"status": "error", "message": "Unknown agent"}), 400

    prompt = prompts[agent_name]

    # Run Claude Code
    try:
        result = subprocess.Popen(
            ["claude", "-p", prompt],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )
        stdout, stderr = result.communicate(timeout=120)

        if result.returncode != 0:
            return jsonify({
                "status": "error",
                "message": stderr
            }), 500

        return jsonify({
            "status": "ok",
            "message": f"{agent_name} agent completed"
        })

    except subprocess.TimeoutExpired:
        return jsonify({
            "status": "error",
            "message": "Agent timed out after 120 seconds"
        }), 500

    except FileNotFoundError:
        return jsonify({
            "status": "error",
            "message": "Claude Code not found. Is it installed?"
        }), 500

# ─── Read Output Files ────────────────────────────────────────
@app.route('/api/output/<filename>')
def get_output(filename):
    allowed = [
        'topics.md',
        'hooks.md',
        'script.md',
        'scores.json',
        'metadata.md',
        'repurpose.md'
    ]

    if filename not in allowed:
        return jsonify({"status": "error", "message": "File not allowed"}), 400

    filepath = os.path.join('outputs', filename)

    if not os.path.exists(filepath):
        return jsonify({"status": "empty", "content": ""}), 200

    with open(filepath, 'r') as f:
        content = f.read()

    return jsonify({"status": "ok", "content": content})

# ─── Start ────────────────────────────────────────────────────
if __name__ == '__main__':
    os.makedirs('outputs', exist_ok=True)
    print("\n Content Engine running at http://localhost:5000\n")
    app.run(debug=True, port=5000)
